# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7adf50dbb73cebfc10460b37e862ac47a08b1a82b0fc1a64c4994fb30b594717ca1b45fa8e3f29d673e27dac5520885219bceb9eb8912821a4accacf8235c874

test:
  secret_key_base: bd75816ba270461267613e993d0b286605e1022abbf6f786e93a20010bcd4d79d386171e8d969d62ec3d945d762ae6b38845af0f2196eb5c0912b160709b816b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
